# Generated by Django 4.2.4 on 2023-09-21 21:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_rename_type_stay_type_of_stay"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stay",
            old_name="type_of_stay",
            new_name="stay_type",
        ),
        migrations.AlterField(
            model_name="stay",
            name="type_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="stay_type"
            ),
        ),
    ]
