# Generated by Django 5.0.6 on 2024-06-25 06:18

import core.models
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hordak", "0038_alter_account_id_alter_leg_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hordak.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
            bases=("hordak.account",),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=254, region=None
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Infos",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="item_images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=1, verbose_name="Stock Quantity"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active?")),
                (
                    "reservation_option",
                    models.BooleanField(
                        default=False, verbose_name="Reservation Option?"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Long description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        default="Short description",
                        max_length=280,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("item", models.CharField(max_length=50, verbose_name="Item")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "price_per_unit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price_per_unit",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price Per Unit",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hordak.transaction",
                        verbose_name="Summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Detail",
                "verbose_name_plural": "Transaction Details",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "cutoff_day",
                    models.SmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MaxValueValidator(31),
                            django.core.validators.MinValueValidator(-1),
                        ],
                        verbose_name="Cutoff Day",
                    ),
                ),
                (
                    "due_day",
                    models.SmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MaxValueValidator(31),
                            django.core.validators.MinValueValidator(-1),
                        ],
                        verbose_name="Due Day",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None, verbose_name="Phone"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, null=True, verbose_name="Address"),
                ),
                (
                    "city",
                    models.CharField(max_length=255, null=True, verbose_name="City"),
                ),
                (
                    "prefecture",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Prefecture"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hordak.account"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
            },
        ),
        migrations.CreateModel(
            name="Procurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Price"
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(verbose_name="Quantity")),
                (
                    "procured_on",
                    core.models.PendulumDateTimeField(verbose_name="Procured On"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement",
                "verbose_name_plural": "Procurements",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "invoiced_on",
                    core.models.PendulumDateTimeField(verbose_name="Invoiced On"),
                ),
                ("due_on", core.models.PendulumDateTimeField(verbose_name="Due On")),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price Per Unit",
                    ),
                ),
                ("procurements", models.ManyToManyField(to="core.transactiondetail")),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
    ]
