# Generated by Django 5.0.6 on 2024-06-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondetail",
            name="type",
            field=models.CharField(
                choices=[("SA", "Sale"), ("PR", "Procurement")],
                default="SA",
                max_length=20,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
    ]
