# Generated by Django 5.0.6 on 2024-06-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_transactiondetail_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiondetail",
            name="type",
            field=models.CharField(
                choices=[("SA", "Sale"), ("PR", "Procurement"), ("PA", "Payment")],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
