# Generated by Django 4.2.6 on 2023-10-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_item_category_alter_item_name_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Active?"),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="Long description", null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="item_images/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="In Stock?"),
        ),
        migrations.AlterField(
            model_name="item",
            name="reservation_option",
            field=models.BooleanField(
                default=False, verbose_name="Reservation Option?"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="short_description",
            field=models.CharField(
                default="Short description",
                max_length=280,
                null=True,
                verbose_name="Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock_quantity",
            field=models.IntegerField(default=1, verbose_name="Stock Quantity"),
        ),
    ]
