# Generated by Django 4.2.4 on 2023-09-18 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_transaction_customer_alter_transaction_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.item",
                verbose_name="Item",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("purchase", "Purchase"),
                    ("return", "Return"),
                    ("deposit", "Bank Deposit"),
                ],
                max_length=30,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_price",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="Total Price"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Transaction Datetime"
            ),
        ),
        migrations.DeleteModel(
            name="Ledger",
        ),
    ]
