# Generated by Django 4.2.6 on 2023-10-27 03:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_item_active_alter_item_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=254, region=None
            ),
            preserve_default=False,
        ),
    ]
