# Generated by Django 4.2.6 on 2023-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_contactinfo_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="name", max_length=100, verbose_name="Category Name"
            ),
            preserve_default=False,
        ),
    ]
