# Generated by Django 5.0.2 on 2024-03-19 00:51

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_category_title_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
    ]
