# Generated by Django 5.0.3 on 2024-05-13 02:05

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_item_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sellable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("purchase", "Purchase"),
                    ("return", "Return"),
                    ("deposit", "Deposit"),
                ],
                max_length=30,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_datetime",
            field=core.models.PendulumDateTimeField(
                default=django.utils.timezone.now, verbose_name="Transaction Datetime"
            ),
        ),
    ]
