# Generated by Django 5.0.3 on 2024-05-13 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_sellable_alter_transaction_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sellable",
        ),
    ]
