# Generated by Django 5.0.3 on 2024-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_delete_sellable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="item",
        ),
        migrations.AddField(
            model_name="transaction",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=19,
                verbose_name="Price Per Unit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="product",
            field=models.CharField(
                default="product", max_length=50, verbose_name="Product"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_price",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="Price Per Unit"
            ),
        ),
    ]
