# Generated by Django 5.0.3 on 2024-05-13 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_transaction_item_transaction_price_per_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_datetime",
        ),
    ]
