# Generated by Django 5.0.3 on 2024-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_transaction_transaction_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="Price Per Unit"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="Price Per Unit"
            ),
        ),
    ]
