# Generated by Django 5.0.3 on 2024-05-15 05:22

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_item_price_alter_transaction_price_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
    ]
