# Generated by Django 5.0.6 on 2024-05-15 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_item_created_at_item_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="in_stock",
        ),
    ]
