# Generated by Django 5.0.6 on 2024-05-15 06:25

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_item_in_stock"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="item",
            managers=[
                ("in_stock", django.db.models.manager.Manager()),
            ],
        ),
    ]
