# Generated by Django 5.0.6 on 2024-05-21 02:44

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_item_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("due_on", recurrence.fields.RecurrenceField()),
                ("cutoff_on", models.DurationField()),
            ],
        ),
    ]
