# Generated by Django 5.0.6 on 2024-05-21 03:02

import relativedeltafield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="cutoff_on",
            field=relativedeltafield.fields.RelativeDeltaField(),
        ),
    ]
