# Generated by Django 5.0.6 on 2024-05-21 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_vendor_cutoff_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="cutoff_on",
        ),
    ]
