# Generated by Django 5.0.6 on 2024-05-22 06:53

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_vendor_cutoff_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"verbose_name": "Vendor", "verbose_name_plural": "Vendors"},
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="due_on",
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="cutoff_day",
            field=models.SmallIntegerField(
                default=30,
                validators=[
                    django.core.validators.MaxValueValidator(31),
                    django.core.validators.MinValueValidator(-1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="due_day",
            field=models.SmallIntegerField(
                default=30,
                validators=[
                    django.core.validators.MaxValueValidator(31),
                    django.core.validators.MinValueValidator(-1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("procurement", "Procurement"),
                    ("return", "Return"),
                    ("deposit", "Deposit"),
                ],
                max_length=30,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="Procurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("product", models.CharField(max_length=50, verbose_name="Product")),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Price"
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(verbose_name="Quantity")),
                (
                    "procured_on",
                    core.models.PendulumDateTimeField(verbose_name="Procured On"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement",
                "verbose_name_plural": "Procurements",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "invoiced_on",
                    core.models.PendulumDateTimeField(verbose_name="Invoiced On"),
                ),
                ("due_on", core.models.PendulumDateTimeField(verbose_name="Due On")),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
                    ),
                ),
                ("procurements", models.ManyToManyField(to="core.procurement")),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
    ]
