# Generated by Django 5.0.6 on 2024-05-24 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_vendor_options_remove_vendor_due_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.item"
            ),
        ),
    ]
