# Generated by Django 5.0.6 on 2024-05-24 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_procurement_product"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="item",
            managers=[],
        ),
    ]
