# Generated by Django 5.0.6 on 2024-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_item_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_on",
            field=models.DateTimeField(verbose_name="Due On"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoiced_on",
            field=models.DateTimeField(verbose_name="Invoiced On"),
        ),
    ]
