# Generated by Django 5.0.6 on 2024-05-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_invoice_due_on_alter_invoice_invoiced_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_on",
            field=models.DateTimeField(verbose_name="Due On"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoiced_on",
            field=models.DateTimeField(verbose_name="Invoiced On"),
        ),
    ]
