# Generated by Django 5.0.6 on 2024-05-29 02:42

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_invoice_due_on_alter_invoice_invoiced_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_on",
            field=core.models.PendulumDateTimeField(verbose_name="Due On"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoiced_on",
            field=core.models.PendulumDateTimeField(verbose_name="Invoiced On"),
        ),
    ]
