# Generated by Django 5.0.6 on 2024-05-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_invoice_due_on_alter_invoice_invoiced_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invooice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
