# Generated by Django 5.0.6 on 2024-05-29 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_invooice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invooice",
            name="editable_dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
