# Generated by Django 5.0.6 on 2024-06-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_invooice_editable_dt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invooice",
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
