# Generated by Django 5.0.6 on 2024-06-13 00:13

import core.models
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_delete_invooice_invoice_amount"),
        ("hordak", "0038_alter_account_id_alter_leg_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("product", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price_per_unit",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="JPY", max_digits=19
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Item",
                "verbose_name_plural": "Transaction Items",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price",
            ),
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hordak.transaction",
                    ),
                ),
                ("items", models.ManyToManyField(to="core.transactionitem")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
