# Generated by Django 5.0.6 on 2024-06-14 01:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_transactionitem_item_price_currency_alter_item_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
