# Generated by Django 5.0.6 on 2024-06-17 05:54

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_setting"),
        ("hordak", "0038_alter_account_id_alter_leg_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactiondetail",
            options={
                "verbose_name": "Transaction Detail",
                "verbose_name_plural": "Transaction Details",
            },
        ),
        migrations.RemoveField(
            model_name="transactionitem",
            name="product",
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="item",
            field=models.CharField(default=2, max_length=50, verbose_name="Item"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactiondetail",
            name="summary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hordak.transaction",
                verbose_name="Summary",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="price_per_unit",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Per Unit",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
    ]
