# Generated by Django 5.0.6 on 2024-06-17 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_transactiondetail_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
