# Generated by Django 5.0.6 on 2024-06-18 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionitem",
            name="item",
        ),
    ]
