# Generated by Django 5.0.6 on 2024-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_remove_transactionitem_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="name",
            field=models.CharField(
                default="Reservation", max_length=50, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
