# Generated by Django 5.0.6 on 2024-06-19 02:22

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_transactionitem_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiondetail",
            name="items",
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="item",
            field=models.CharField(default="Banan", max_length=50, verbose_name="Item"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="price_per_unit",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Per Unit",
            ),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="price_per_unit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TransactionItem",
        ),
    ]
