# Generated by Django 5.0.6 on 2024-06-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_remove_transactiondetail_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="procurements",
            field=models.ManyToManyField(to="core.transactiondetail"),
        ),
    ]
