# Generated by Django 5.0.6 on 2024-06-19 05:56

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_invoice_procurements"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Per Unit",
            ),
        ),
    ]
