# Generated by Django 5.0.6 on 2024-06-25 06:18

import customer.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    customer.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    customer.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="TicketNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    customer.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    customer.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "Ticket Note",
                "verbose_name_plural": "Ticket Notes",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    customer.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    customer.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                ("notes", models.ManyToManyField(to="customer.ticketnote")),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
    ]
