# Generated by Django 4.2.6 on 2023-10-23 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_ticketnote_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="note",
            new_name="notes",
        ),
    ]
