# Generated by Django 4.2.6 on 2023-10-26 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_rename_note_ticket_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="is_resolved",
            new_name="is_closed",
        ),
    ]
