# Generated by Django 5.0.3 on 2024-05-14 10:35

import customer.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_ticketnote_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=customer.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=customer.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=customer.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="updated_at",
            field=customer.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketnote",
            name="created_at",
            field=customer.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketnote",
            name="updated_at",
            field=customer.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
    ]
