"""
Django settings for winvillage project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import environ
from django.apps import apps

# For translation
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
DJANGO_ENVIRONMENT = env("DJANGO_ENVIRONMENT", default="dev")
if DJANGO_ENVIRONMENT == "dev":
    env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

DEBUG = env.bool("DJANGO_DEBUG", default=True)

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["winvillage.jp"])

if not DEBUG:
    CSRF_TRUSTED_ORIGINS = ["https://*.winvillage.jp", "https://winvillage.jp"]
    CSRF_COOKIE_DOMAIN = ".winvillage.jp"
    CSRF_COOKIE_SECURE = True


# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env('SECRET_KEY')
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-weadmo#f0(uj@@sd=+#1=q^iqcoenqpc7zqy8nlf5gas&um_pa",
)

DJANGO_SUPER_USER_NAME = env("DJANGO_SUPER_USER_NAME")
DJANGO_SUPER_USER_EMAIL = env("DJANGO_SUPER_USER_EMAIL")
DJANGO_SUPER_USER_PASSWORD = env("DJANGO_SUPER_USER_PASSWORD", default=None)

# Application definition

DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # Handy template tags
    "django.contrib.admin",
    "django.forms",
]

THIRD_PARTY_APPS = [
    "django_htmx",
    "django_tailwind_cli",
    "widget_tweaks",
    "render_block",
    "django_extensions",
    "parler",
    "whitenoise",
    "rosetta",
    "responsive_images",
    "phonenumbers",
    "slippers",
]

if DEBUG:
    THIRD_PARTY_APPS += ["django_browser_reload", "pattern_library"]

LOCAL_APPS = [
    "users",
    "core",
    "reservations",
    "winadmin",
    "customer",
]

# MENU_SELECT_PARENTS = True
# MENU_HIDE_EMPTY = True
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# MIGRATIONS
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#migration-modules
MIGRATION_MODULES = {"sites": "core.contrib.sites.migrations"}

# AUTHENTICATION
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#authentication-backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model
AUTH_USER_MODEL = "users.User"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-redirect-url
LOGIN_REDIRECT_URL = "users:redirect"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-url
# LOGIN_URL = "login_page"

# PASSWORDS
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#password-hashers
PASSWORD_HASHERS = [
    # https://docs.djangoproject.com/en/dev/topics/auth/passwords/#using-argon2-with-django
    # "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# MIDDLEWARE
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
]

if DEBUG:
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "winvillage.urls"

# Django 4.1 and above caches templates when DEBUG is true.
# See: https://nickjanetakis.com/blog/django-4-1-html-templates-are-cached-by-default-with-debug-true

default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]
TEMPLATE_BUILTINS = ["slippers.templatetags.slippers"]
if apps.is_installed("pattern_library"):
    TEMPLATE_BUILTINS.append("pattern_library.loader_tags")
# APP_DIRS unnecessary if django.template.loaders.app_directories.Loader is set.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/../templates/"],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": default_loaders if DEBUG else cached_loaders,
            "builtins": [
                "slippers.templatetags.slippers",
            ],
        },
    },
]

# Needed for pattern_library to show detailed error messages
if DEBUG:
    X_FRAME_OPTIONS = "SAMEORIGIN"

PATTERN_LIBRARY = {
    # Groups of templates for the pattern library navigation. The keys
    # are the group titles and the values are lists of template name prefixes that will
    # be searched to populate the groups.
    "SECTIONS": (
        ("navigations", ["patterns/navigations"]),
        ("buttons", ["patterns/buttons"]),
        ("pages", ["patterns/pages"]),
    ),
    # Configure which files to detect as templates.
    "TEMPLATE_SUFFIX": ".html",
    # Set which template navigations should be rendered inside of,
    # so they may use page-level component dependencies like CSS.
    "PATTERN_BASE_TEMPLATE_NAME": "patterns/base.html",
    # Any template in BASE_TEMPLATE_NAMES or any template that extends a template in
    # BASE_TEMPLATE_NAMES is a "page" and will be rendered as-is without being wrapped.
    "BASE_TEMPLATE_NAMES": ["patterns/base_page.html"],
}

# FORMS
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/ref/forms/renderers/#built-in-template-form-renderers
# FORM_RENDERER = 'django.forms.renderers.DjangoTemplates' (default)
# This renderer uses a standalone DjangoTemplates engine (unconnected to what you might have configured in the
# TEMPLATES setting). It loads templates first from the built-in form templates directory in django/forms/templates
# and then from the installed apps’ templates directories using the app_directories loader.

# If you want to render templates with customizations from your TEMPLATES setting, such as context processors for
# example, use the TemplatesSetting renderer.

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# FIXTURES
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#fixture-dirs
FIXTURE_DIRS = (str(BASE_DIR / "fixtures"),)

WSGI_APPLICATION = "winvillage.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": env.db(),
    "extra": env.db_url("SQLITE_URL", default="sqlite:////tmp/my-tmp-sqlite.db"),
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = "en"
LANGUAGE_CODE = "ja"

# https://docs.djangoproject.com/en/dev/ref/settings/#languages
# from django.utils.translation import gettext_lazy as _
LANGUAGES = (
    ("en", _("English")),
    ("ja", _("Japanese")),
)
# Command for making Japanese messages:
# django-admin makemessages -l ja
LOCALE_PATHS = [
    str(BASE_DIR / "locale"),
]

PARLER_LANGUAGES = {
    1: (
        {
            "code": "en-us",
        },  # English
        {
            "code": "ja",
        },  # Japanese
    ),
    "default": {
        "fallbacks": ["ja"],
        "hide_untranslated": False,
    },
}

# Local time zone. Choices are
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# though not all of them may be available with every OS.
# In Windows, this must be set to your system time zone.
TIME_ZONE = "UTC"
USE_TZ = True
USE_I18N = True
USE_L10N = True
SITE_ID = 1

# STATIC
# ------------------------------------------------------------------------------
WHITENOISE_USE_FINDERS = True

# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(BASE_DIR / "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = [str(BASE_DIR / "static")]
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
if DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# MEDIA
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str(BASE_DIR / "media")
# https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DATABASES["default"]["ATOMIC_REQUESTS"] = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# EMAIL
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#email-backend

EMAIL_BACKEND = env(
    "DJANGO_EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
SENDGRID_API_KEY = env("SENDGRID_API_KEY")

# https://docs.djangoproject.com/en/dev/ref/settings/#email-timeout
EMAIL_TIMEOUT = 5
DEFAULT_FROM_EMAIL = "admin@winvillage.jp"
EMAIL_HOST = "localhost"
EMAIL_PORT = "1025"

# Phone Numbers
PHONENUMBER_DB_FORMAT = "INTERNATIONAL"
PHONENUMBER_DEFAULT_REGION = "JP"
PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"

# ADMIN
# ------------------------------------------------------------------------------
# Django Admin URL.
ADMIN_URL = env("DJANGO_ADMIN_URL", default="django-admin/")
# https://docs.djangoproject.com/en/dev/ref/settings/#admins
ADMINS = [("Micah Jonah Killian", "micah@killianarts.online")]
# https://docs.djangoproject.com/en/dev/ref/settings/#managers
MANAGERS = ADMINS

# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#logging
# See https://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}
# Square settings
SQUARE_SETTINGS = {
    "SQUARE_APPLICATION_ID": env("SQUARE_APPLICATION_ID"),
    "SQUARE_ACCESS_TOKEN": env("SQUARE_ACCESS_TOKEN"),
    "SQUARE_LOCATION_ID": env("SQUARE_LOCATION_ID"),
    "SQUARE_CURRENCY": env("SQUARE_CURRENCY", default="JPY"),
    "SQUARE_ENVIRONMENT": env("SQUARE_ENVIRONMENT", default="sandbox"),
}

REDIS_URL = env("REDIS_URL", default="redis://127.0.0.1:6379/0")

# Celery Settings
CELERY_BROKER_URL = REDIS_URL
CELERYD_TASK_SOFT_TIME_LIMIT = 60
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_CREATE_MISSING_QUEUES = True
