# Generated by Django 5.0.6 on 2024-06-25 06:18

import core.models
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import model_utils.fields
import recurrence.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "recurrences",
                    recurrence.fields.RecurrenceField(verbose_name="Recurrences"),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "number_of_adults",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        default=1,
                        verbose_name="Number of Adults",
                    ),
                ),
                (
                    "price_overnight_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price_overnight",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price Overnight",
                    ),
                ),
                (
                    "price_short_term_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price_short_term",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price Short-term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing tier",
                "verbose_name_plural": "Pricing tiers",
            },
        ),
        migrations.CreateModel(
            name="PricingTierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "minimum_number_of_adults",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "maximum_number_of_adults",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "price_overnight_child_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price_overnight_child",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price Per Child Overnight",
                    ),
                ),
                (
                    "price_short_term_child_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price_short_term_child",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=19,
                        verbose_name="Price Per Child Short-Term",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.CreateModel(
            name="ReservationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("base_url", models.URLField(default="http://localhost:8000")),
            ],
            options={
                "verbose_name": "Reservation Token",
                "verbose_name_plural": "Reservation Tokens",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Room Tier",
                "verbose_name_plural": "Rooms Tiers",
            },
        ),
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("not_reserved", "Not Reserved"),
                            ("reserved", "Reserved"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_reserved",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "number_of_adults",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="Number of Adults",
                    ),
                ),
                (
                    "number_of_children",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        default=0,
                        null=True,
                        verbose_name="Number of Children",
                    ),
                ),
                (
                    "start",
                    core.models.PendulumDateTimeField(
                        blank=True, null=True, verbose_name="Start"
                    ),
                ),
                (
                    "end",
                    core.models.PendulumDateTimeField(
                        blank=True, null=True, verbose_name="End"
                    ),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("JPY", "JPY ￥")],
                        default="JPY",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="JPY",
                        max_digits=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stay",
                "verbose_name_plural": "Stays",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    core.models.PendulumDateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "updated_at",
                    core.models.PendulumDateTimeField(auto_now=True, null=True),
                ),
                (
                    "ordered",
                    models.BooleanField(default=False, verbose_name="Ordered?"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
