# Generated by Django 4.2.6 on 2023-10-14 06:39

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    (0, "Not Reserved"),
                    (1, "Reserved"),
                    (2, "Checked In"),
                    (3, "Checked Out"),
                    (4, "Cancelled"),
                ],
                default=0,
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
