# Generated by Django 5.0.2 on 2024-03-19 00:51

import core.models
import django.db.models.deletion
import phonenumber_field.modelfields
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_category_created_at_alter_category_updated_at_and_more"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "recurrences",
                    recurrence.fields.RecurrenceField(verbose_name="Recurrences"),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_adults",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        default=1,
                        verbose_name="Number of Adults",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Price per Night"
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Price per Hour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing tier",
                "verbose_name_plural": "Pricing tiers",
            },
        ),
        migrations.CreateModel(
            name="PricingTierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("campaigns", models.ManyToManyField(to="reservations.campaign")),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Room Tier",
                "verbose_name_plural": "Rooms Tiers",
            },
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="contact_info",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_datetime",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="price",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="stay_type",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="type_changed",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="reservations.orderitem"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.item"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(max_length=255, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(max_length=50, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=255, null=True, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="end",
            field=core.models.PendulumDateTimeField(
                blank=True, null=True, verbose_name="End"
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=1,
                null=True,
                verbose_name="Number of Adults",
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="number_of_children",
            field=models.IntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                ],
                default=0,
                null=True,
                verbose_name="Number of Children",
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="start",
            field=core.models.PendulumDateTimeField(
                blank=True, null=True, verbose_name="Start"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False, verbose_name="Ordered?"),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ordered Date"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="stay",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="stay",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="tier_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.pricingtiergroup",
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.room",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.roomtier",
                verbose_name="Room Tier",
            ),
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="room_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservations.roomtier"
            ),
        ),
    ]
