# Generated by Django 4.2.6 on 2023-11-01 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="end_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="End"
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Start"
            ),
        ),
    ]
