# Generated by Django 4.2.6 on 2023-10-14 06:43

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_alter_stay_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("not_reserved", "Not Reserved"),
                    ("reserved", "Reserved"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_reserved",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
