# Generated by Django 4.2.3 on 2023-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0002_category_contactinfo_item_orderitem_reservation_stay_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="price",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
