# Generated by Django 5.0.2 on 2024-03-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0002_campaign_pricingtier_pricingtiergroup_room_roomtier_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtiergroup",
            name="room_tier",
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="room_tier",
            field=models.ManyToManyField(to="reservations.roomtier"),
        ),
    ]
