# Generated by Django 4.2.3 on 2023-08-03 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0003_address_category_customer_food_grill_item_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationoption",
            options={
                "verbose_name": "Reservation Option",
                "verbose_name_plural": "Reservation Options",
            },
        ),
    ]
