# Generated by Django 5.0.2 on 2024-03-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_remove_pricingtiergroup_room_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtiergroup",
            name="pricing_tiers",
            field=models.ManyToManyField(to="reservations.pricingtier"),
        ),
    ]
