# Generated by Django 5.0.2 on 2024-03-19 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_pricingtiergroup_pricing_tiers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingtiergroup",
            old_name="room_tier",
            new_name="room_tiers",
        ),
    ]
