# Generated by Django 4.2.3 on 2023-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_alter_stay_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="price",
            field=models.DecimalField(decimal_places=4, default=10000.0, max_digits=19),
        ),
    ]
