# Generated by Django 5.0.2 on 2024-03-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_rename_room_tier_pricingtiergroup_room_tiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtier",
            name="price_per_hour",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="price_per_night",
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="price_overnight",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=19,
                verbose_name="Price Overnight",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="price_short_term",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=19,
                verbose_name="Price Short-term",
            ),
            preserve_default=False,
        ),
    ]
