# Generated by Django 4.2.7 on 2023-11-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_alter_stay_end_datetime_alter_stay_start_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="end_datetime",
            field=models.DateTimeField(null=True, verbose_name="End"),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start_datetime",
            field=models.DateTimeField(null=True, verbose_name="Start"),
        ),
    ]
