# Generated by Django 5.0.2 on 2024-03-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_remove_pricingtier_price_per_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True, null=True, to="reservations.campaign"
            ),
        ),
    ]
