# Generated by Django 4.2.4 on 2023-08-30 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_contactinfo_customer_transaction_ledger"),
        ("reservations", "0006_remove_item_category_alter_orderitem_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="contact_info",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="contact_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contactinfo",
            ),
        ),
        migrations.DeleteModel(
            name="ContactInfo",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
