# Generated by Django 4.2.3 on 2023-08-03 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0006_rename_person_contactinfo_remove_customer_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="contact_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.contactinfo",
            ),
        ),
    ]
