# Generated by Django 5.0.2 on 2024-03-21 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_alter_pricingtiergroup_campaigns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtiergroup",
            name="pricing_tiers",
        ),
    ]
