# Generated by Django 4.2.3 on 2023-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_reservation_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="type",
            field=models.CharField(
                choices=[("hourly", "Hourly"), ("overnight", "Overnight")],
                max_length=255,
            ),
        ),
    ]
