# Generated by Django 4.2.7 on 2023-11-14 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_alter_stay_end_datetime_alter_stay_start_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stay",
            old_name="end_datetime",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="stay",
            old_name="start_datetime",
            new_name="start_date",
        ),
    ]
