# Generated by Django 4.2.4 on 2023-09-20 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0007_remove_customer_contact_info_remove_customer_user_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stay",
            old_name="type",
            new_name="type_of_stay",
        ),
    ]
