# Generated by Django 4.2.7 on 2023-11-15 02:29

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_rename_end_datetime_stay_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="updated_datetime",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(max_length=50, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=254, null=True, region=None
            ),
        ),
    ]
