# Generated by Django 5.0.2 on 2024-03-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_remove_pricingtiergroup_pricing_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="campaigns",
            field=models.ManyToManyField(to="reservations.campaign"),
        ),
    ]
