# Generated by Django 4.2.3 on 2023-08-07 18:19

import datetime
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_alter_stay_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PurchasedReservationOptions",
        ),
        migrations.AlterField(
            model_name="stay",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 7, 18, 19, 57, 237664, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 7, 18, 19, 57, 237501, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("not_reserved", "Not Reserved"),
                    ("reserved", "Reserved"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_reserved",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="type",
            field=models.CharField(
                choices=[("hourly", "Hourly"), ("overnight", "Overnight")],
                default="hourly",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="ReservedRoom",
        ),
    ]
