# Generated by Django 4.2.7 on 2023-11-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0009_rename_updated_datetime_reservation_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="end_time",
            field=models.TimeField(null=True, verbose_name="End"),
        ),
        migrations.AddField(
            model_name="stay",
            name="start_time",
            field=models.TimeField(null=True, verbose_name="Start"),
        ),
    ]
