# Generated by Django 4.2.3 on 2023-08-07 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0009_delete_purchasedreservationoptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 7, 18, 22, 1, 822537, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 7, 18, 22, 1, 822409, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
