# Generated by Django 5.0.2 on 2024-03-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0009_alter_pricingtiergroup_campaigns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="campaigns",
            field=models.ManyToManyField(blank=True, to="reservations.campaign"),
        ),
    ]
