# Generated by Django 5.0.2 on 2024-03-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0010_alter_pricingtiergroup_campaigns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
