# Generated by Django 4.2.7 on 2023-11-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0010_stay_end_time_stay_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("daily_price", models.DecimalField(decimal_places=4, max_digits=19)),
                ("hourly_price", models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
    ]
