# Generated by Django 4.2.3 on 2023-08-07 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0010_alter_stay_end_datetime_alter_stay_start_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
