# Generated by Django 4.2.7 on 2023-11-16 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_specialdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stay",
            name="price",
        ),
    ]
