# Generated by Django 5.0.3 on 2024-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_alter_pricingtiergroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="roomtier",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
