# Generated by Django 5.0.3 on 2024-04-11 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0012_alter_campaign_name_alter_room_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtiergroup",
            name="maximum_number_of_adults",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="minimum_number_of_adults",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
            preserve_default=False,
        ),
    ]
