# Generated by Django 4.2.8 on 2024-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0012_remove_stay_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday_price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "weekend_price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "weekday_price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "weekend_price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="specialdate",
            old_name="hourly_price",
            new_name="price_per_hour",
        ),
        migrations.RenameField(
            model_name="specialdate",
            old_name="daily_price",
            new_name="price_per_night",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="start_time",
        ),
        migrations.AddField(
            model_name="stay",
            name="end",
            field=models.DateTimeField(null=True, verbose_name="End"),
        ),
        migrations.AddField(
            model_name="stay",
            name="start",
            field=models.DateTimeField(null=True, verbose_name="Start"),
        ),
    ]
