# Generated by Django 5.0.3 on 2024-04-12 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0013_pricingtiergroup_maximum_number_of_adults_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtiergroup",
            name="campaigns",
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="campaigns",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.campaign",
            ),
        ),
    ]
