# Generated by Django 4.2.8 on 2024-01-11 05:35

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0013_defaultprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="end",
            field=core.models.PendulumDateTimeField(null=True, verbose_name="End"),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start",
            field=core.models.PendulumDateTimeField(null=True, verbose_name="Start"),
        ),
    ]
