# Generated by Django 4.2.8 on 2024-01-25 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0014_alter_stay_end_alter_stay_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="defaultprice",
            old_name="weekday_price_per_hour",
            new_name="adult_price_per_hour",
        ),
        migrations.RenameField(
            model_name="defaultprice",
            old_name="weekday_price_per_night",
            new_name="adult_price_per_night",
        ),
        migrations.RenameField(
            model_name="defaultprice",
            old_name="weekend_price_per_hour",
            new_name="child_price_per_hour",
        ),
        migrations.RenameField(
            model_name="defaultprice",
            old_name="weekend_price_per_night",
            new_name="child_price_per_night",
        ),
    ]
