# Generated by Django 5.0.3 on 2024-04-12 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0014_remove_pricingtiergroup_campaigns_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingtiergroup",
            old_name="campaigns",
            new_name="campaign",
        ),
    ]
