# Generated by Django 5.0.3 on 2024-04-12 05:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0015_rename_campaigns_pricingtiergroup_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
    ]
