# Generated by Django 4.2.8 on 2024-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0015_rename_weekday_price_per_hour_defaultprice_adult_price_per_hour_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stay",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="number_of_children",
            field=models.IntegerField(
                choices=[
                    (0, "Zero"),
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "pricing_tiers",
                    models.ManyToManyField(to="reservations.pricingtier"),
                ),
            ],
        ),
    ]
