# Generated by Django 5.0.1 on 2024-02-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0016_pricingtier_stay_number_of_adults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtier",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.room",
            ),
        ),
    ]
