# Generated by Django 5.0.3 on 2024-04-16 04:02

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0016_campaign_created_at_campaign_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="roomtier",
            name="created_at",
            field=core.models.PendulumDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="roomtier",
            name="updated_at",
            field=core.models.PendulumDateTimeField(auto_now=True, null=True),
        ),
    ]
