# Generated by Django 5.0.2 on 2024-02-20 04:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0017_pricingtier_number_of_adults_stay_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="end",
            field=core.models.PendulumDateTimeField(
                blank=True, null=True, verbose_name="End"
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="start",
            field=core.models.PendulumDateTimeField(
                blank=True, null=True, verbose_name="Start"
            ),
        ),
    ]
