# Generated by Django 5.0.3 on 2024-04-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0017_room_created_at_room_updated_at_roomtier_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
    ]
