# Generated by Django 5.0.2 on 2024-02-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0018_alter_stay_end_alter_stay_number_of_adults_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                ],
                default=1,
            ),
        ),
    ]
