# Generated by Django 5.0.3 on 2024-04-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0018_stay_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtiergroup",
            name="price_child",
            field=models.DecimalField(
                decimal_places=4,
                default=4000,
                max_digits=19,
                verbose_name="Price Per Child",
            ),
            preserve_default=False,
        ),
    ]
