# Generated by Django 5.0.3 on 2024-04-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0019_pricingtiergroup_price_child"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtiergroup",
            name="price_child",
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="price_overnight_child",
            field=models.DecimalField(
                decimal_places=4,
                default=5000,
                max_digits=19,
                verbose_name="Price Per Child Overnight",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="price_short_term_child",
            field=models.DecimalField(
                decimal_places=4,
                default=1000,
                max_digits=19,
                verbose_name="Price Per Child Short-Term",
            ),
            preserve_default=False,
        ),
    ]
