# Generated by Django 5.0.2 on 2024-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0020_alter_stay_number_of_adults_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="number_of_children",
            field=models.IntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
