# Generated by Django 5.0.3 on 2024-05-01 05:13

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_ticketnote_user"),
        ("reservations", "0020_remove_pricingtiergroup_price_child_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="room",
            managers=[
                ("checked_in_rooms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
    ]
