# Generated by Django 5.0.2 on 2024-02-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0021_alter_stay_number_of_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtier",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=1,
                null=True,
            ),
        ),
    ]
