# Generated by Django 5.0.3 on 2024-05-01 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0021_alter_room_managers_order_customer"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="room",
            managers=[],
        ),
    ]
