# Generated by Django 5.0.2 on 2024-02-27 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0022_alter_pricingtier_number_of_adults_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stay",
            name="stay_type",
        ),
        migrations.RemoveField(
            model_name="stay",
            name="type_changed",
        ),
    ]
