# Generated by Django 5.0.3 on 2024-05-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_ticketnote_user"),
        ("reservations", "0022_alter_room_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="phone",
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.customer",
            ),
        ),
    ]
