# Generated by Django 5.0.3 on 2024-05-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0023_remove_reservation_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="order_items",
            field=models.ManyToManyField(
                blank=True, null=True, to="reservations.orderitem"
            ),
        ),
    ]
