# Generated by Django 5.0.2 on 2024-02-29 04:19

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0023_remove_stay_stay_type_remove_stay_type_changed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.DeleteModel(
            name="DefaultPrice",
        ),
        migrations.AlterModelOptions(
            name="pricingtier",
            options={
                "verbose_name": "Pricing tier",
                "verbose_name_plural": "Pricing tiers",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False, verbose_name="Ordered?"),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ordered Date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=1,
                verbose_name="Number of Adults",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price_per_hour",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="Price per Hour"
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="Price per Night"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(max_length=50, null=True, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=254, null=True, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="stay",
            name="number_of_adults",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=1,
                null=True,
                verbose_name="Number of Adults",
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="number_of_children",
            field=models.IntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                ],
                default=0,
                null=True,
                verbose_name="Number of Children",
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
