# Generated by Django 5.0.3 on 2024-05-13 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0025_alter_reservation_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ordered_date",
        ),
    ]
