# Generated by Django 5.0.3 on 2024-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0026_remove_order_ordered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
