# Generated by Django 5.0.3 on 2024-05-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0027_alter_stay_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtier",
            name="price_overnight",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="Price Overnight"
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price_short_term",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="Price Short-term"
            ),
        ),
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="price_overnight_child",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=19,
                verbose_name="Price Per Child Overnight",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="price_short_term_child",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=19,
                verbose_name="Price Per Child Short-Term",
            ),
        ),
    ]
