# Generated by Django 5.0.6 on 2024-06-18 01:58

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0028_alter_pricingtier_price_overnight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtier",
            name="price_overnight_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="price_short_term_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="price_overnight_child_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="pricingtiergroup",
            name="price_short_term_child_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")], default="JPY", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("JPY", "JPY ￥")],
                default="JPY",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price_overnight",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Overnight",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price_short_term",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Short-term",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="price_overnight_child",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Per Child Overnight",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtiergroup",
            name="price_short_term_child",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="JPY",
                max_digits=19,
                verbose_name="Price Per Child Short-Term",
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="JPY",
                max_digits=16,
                null=True,
            ),
        ),
    ]
