# Generated by Django 5.0.6 on 2024-06-18 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0029_pricingtier_price_overnight_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stay",
            name="status_changed",
        ),
    ]
