# Generated by Django 4.2.4 on 2023-08-30 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_contactinfo_customer_transaction_ledger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("purchase", "Purchase"),
                    ("return", "Return"),
                    ("deposit", "Bank Deposit"),
                ],
                max_length=30,
            ),
        ),
    ]
