# Generated by Django 4.2.4 on 2023-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_transaction_customer_alter_transaction_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="reservation_option",
            field=models.BooleanField(default=False),
        ),
    ]
