# Generated by Django 5.0.6 on 2024-06-25 06:18

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "recurrence",
                    recurrence.fields.RecurrenceField(verbose_name="Recurrences"),
                ),
            ],
            options={
                "verbose_name": "Special Date",
                "verbose_name_plural": "Special Dates",
            },
        ),
    ]
