# Generated by Django 5.0.2 on 2024-03-11 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("winadmin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialdate",
            old_name="recurrence_rule",
            new_name="recurrence",
        ),
    ]
