# Generated by Django 5.0.2 on 2024-03-11 04:44

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("winadmin", "0002_rename_recurrence_rule_specialdate_recurrence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialdate",
            options={
                "verbose_name": "Special Date",
                "verbose_name_plural": "Special Dates",
            },
        ),
        migrations.AlterField(
            model_name="specialdate",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="specialdate",
            name="recurrence",
            field=recurrence.fields.RecurrenceField(verbose_name="Recurrence"),
        ),
    ]
