# Generated by Django 5.0.2 on 2024-03-14 06:47

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("winadmin", "0003_alter_specialdate_options_alter_specialdate_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialdate",
            name="recurrence",
            field=recurrence.fields.RecurrenceField(verbose_name="Recurrences"),
        ),
    ]
